"""Script for performance evaluation of GN AI systems using DSPy.Evaluate and custom decision function"""

import argparse
import asyncio
import os
import uuid
from concurrent.futures import ThreadPoolExecutor
from typing import Any

import dspy
import pandas as pd
import torch
from dotenv import load_dotenv
from gnais.search.agent import agent_search
from gnais.search.classification import classify_search
from gnais.search.corpus import (
    create_ensemble_retriever,
    get_chroma_db,
    get_docs,
    init_chroma_db,
)
from gnais.search.grag import graph_rag_search
from gnais.search.rag import rag_search
from gnais.search.ragent import hybrid_search


def get_dataset(
    dataset_path: str,
    column_names: list[str] = ["query", "answer"],
) -> list[dspy.Example]:
    data = pd.read_csv(
        dataset_path,
        usecols=column_names,
    )
    data_dicts = data[column_names].to_dict(orient="records")
    evaluation_set = [
        dspy.Example({name: x[name] for name in column_names}).with_inputs(
            column_names[0]
        )
        for x in data_dicts
    ]
    return evaluation_set


def mark(
    query: str,
    generated_response: str,
    true_response: str,
) -> float:

    assess = dspy.ChainOfThought("question -> answer: int")
    context = f"""Your task is to compare elements of response in the answer generated by AI to the ones in the true answer.
    You must compare only informations that are strictly relevant to the query.
    User query: {query}\nAI answer: {generated_response}\nTrue answer: {true_response}"""

    tp_question = f"{context}\nThe objective is to compute the number of true positives by comparing the generated answer and true answer. True positives are elements of response to the query that are mentioned in the generated answer and somewhat highlighted in the true answer as well. How many true positives do you count?"
    tp_score = assess(question=tp_question).get("answer")

    fp_question = f"{context}\nThe objective is to compute the number of false positives by comparing the generated answer and true answer. False positives are explicit and highly relevant elements of response to the query that are present in the generated answer and are not supported in any ways by the true answer. They should not be covered by a reformulation of the true answer. How many false positives do you count?"
    fp_score = assess(question=fp_question).get("answer")

    fn_question = f"{context}\nThe objective is to compute the number of false negatives by comparing the generated answer and true answer. False negatives are elements of response to the query that feature in the true answer and are not supported by the generated answer. How many false negatives do you count?"
    fn_score = assess(question=fn_question).get("answer")

    print(
        f"Question: {query}\nTrue answer: {true_response}\nAI answer: {generated_response.get('answer')}"
    )
    print(f"TP: {tp_score}\nFP: {fp_score}\nFN: {fn_score}")

    tiny_term = 1e-10
    precision = tp_score / (tp_score + fp_score + tiny_term)
    recall = tp_score / (tp_score + fn_score + tiny_term)
    f1 = (2 * tp_score) / ((2 * tp_score) + fp_score + fn_score + tiny_term)

    return precision, recall, f1


def evaluator(
    gold: dspy.Example,
    pred: str,
    trace=None,
    pred_name=None,
    pred_trace=None,
) -> int:
    query = gold["query"]
    true_response = gold["answer"]
    precision, recall, f1 = mark(query, pred, true_response)
    return 1 if (f1 >= 0.6 or recall >= 0.7 or precision >= 0.7) else 0


def run_eval(
    runner: dspy.Evaluate,
    evaluation_set: list[dspy.Example],
    search_func: Any,
) -> dspy.evaluate.EvaluationResult:

    search = dspy.Tool(
        name="search",
        desc="Answer the question asked by the user.",
        args={
            "query": {
                "type": "string",
                "desc": "question asked by the user",
            },
        },
        func=search_func,
    )

    class Signature(dspy.Signature):
        query: str = dspy.InputField(desc="User question")
        answer: str = dspy.OutputField(
            desc="Answer to user's query with details and explanations"
        )

    # Wrap hybrid search into a DSPy module that is compatible with DSPy evaluation
    program = dspy.ReAct(
        signature=Signature, tools=[search], max_iters=2
    )  # limit iterations

    return runner(program)


_TOOL_EXECUTOR = ThreadPoolExecutor(max_workers=1, thread_name_prefix="search")


def _run_async(async_fn, *args, **kwargs):
    """Run async function in a separate thread with a fresh event loop"""

    def _worker():
        return asyncio.run(async_fn(*args, **kwargs))

    return _TOOL_EXECUTOR.submit(_worker).result()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--env-file", default=".env", help="Path to .env file")
    args = parser.parse_args()

    load_dotenv(dotenv_path=args.env_file)

    CORPUS_PATH = os.getenv("CORPUS_PATH")
    DB_PATH = os.getenv("DB_PATH")
    SPARQL_ENDPOINT = os.getenv("SPARQL_ENDPOINT")
    DATASET_PATH = os.getenv("DATASET_PATH")
    OUTPUT_PATH = os.getenv("OUTPUT_PATH")
    SEED = int(os.getenv("SEED"))
    MODEL_NAME = os.getenv("MODEL_NAME")
    MODEL_TYPE = int(os.getenv("MODEL_TYPE"))
    N_ITERATIONS = int(os.getenv("N_ITERATIONS"))

    torch.manual_seed(SEED)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(SEED)

    if MODEL_TYPE == 0:
        llm = dspy.LM(
            model=f"openai/{MODEL_NAME}",
            api_base="http://localhost:7501/v1",
            api_key="local",
            model_type="chat",
            max_tokens=10_000,
            n_ctx=10_000,
            seed=2_025,
            temperature=0,
            cache=False,
            verbose=False,
        )
    elif MODEL_TYPE == 1:
        API_KEY = os.getenv("API_KEY")
        llm = dspy.LM(
            MODEL_NAME,
            api_key=API_KEY,
            max_tokens=10_000,
            temperature=0,
            cache=False,
            verbose=False,
        )
    else:
        raise ValueError("MODEL_TYPE must be 0 or 1")

    dspy.configure(lm=llm)
    evaluation_set = get_dataset(DATASET_PATH)
    evaluate = dspy.Evaluate(
        devset=evaluation_set,
        metric=evaluator,
        num_threads=1,
        provide_traceback=True,
        display_table=False,
        display_progress=True,
        lm=llm,
    )
    collection = {}

    # Run evaluation set with LLM only
    base = dspy.ChainOfThought("query -> answer: str")
    base_output = [evaluate(base).get("score") for n in range(N_ITERATIONS)]
    collection["base"] = base_output

    # Wrap search functions inside conveniences
    def rag_digest(query: str, memory: Any = None) -> str:
        async def _run() -> str:
            docs = get_docs(CORPUS_PATH)
            chroma_db = get_chroma_db(embed_model="Qwen/Qwen3-Embedding-0.6B")
            decision = classify_search(query).get("decision")
            retriever = create_ensemble_retriever(
                chroma_db=chroma_db,
                docs=docs,
                keyword_weight=0.7 if decision == "keyword" else 0.5,
            )

            parts = []
            async for chunk in rag_search(
                query=query,
                retriever=retriever,
                memory=memory,
                user_id=str(uuid.uuid4()),
            ):
                parts.append(str(chunk))
            return "".join(parts)

        return _run_async(_run)

    def sparql_digest(
        query: str, handler: Any, memory: Any = None, user_id: str = "default_user"
    ) -> str:
        async def _run():
            parts = []
            async for chunk in handler(
                query=query, sparql_url=SPARQL_ENDPOINT, memory=memory, user_id=user_id
            ):
                parts.append(str(chunk))
            return "".join(parts)

        return _run_async(_run)

    def graph_rag_digest(query: str, memory: Any = None) -> str:
        return sparql_digest(
            query, graph_rag_search, memory=memory, user_id=str(uuid.uuid4())
        )

    def agent_digest(query: str, memory: Any = None) -> str:
        return sparql_digest(
            query, agent_search, memory=memory, user_id=str(uuid.uuid4())
        )

    def hybrid_digest(query: str, memory: Any = None) -> str:
        async def _run():
            final_html = None
            async for event in hybrid_search(
                query, memory=memory, user_id=str(uuid.uuid4())
            ):
                source = event["source"]
                kind = event["kind"]
                content = event["content"]
                if source == "hybrid" and kind == "final":
                    final_html = content
                    break
            return final_html

        return _run_async(_run)

    # Run evaluation set with GN systems
    for system in [rag_digest, graph_rag_digest, agent_digest, hybrid_digest]:
        system_name = " ".join(system.__name__.split("_")[:-1])
        print(f"Running evaluation for {system_name}")
        temp = []
        for n in range(N_ITERATIONS):
            print(f"Iteration {n+1}")
            system_output = run_eval(evaluate, evaluation_set, system)
            temp.append(system_output.get("score"))
        collection[system_name] = temp
        print(f"Evaluation completed for {system_name}")
    final = pd.DataFrame(collection)
    final.to_csv(OUTPUT_PATH, index=False)
