"""Script for performance evaluation of GN AI systems"""

import argparse
import asyncio
import os
from typing import Any

import dspy
import pandas as pd
import torch
from dotenv import load_dotenv
from gnais.search.agent import agent_search
from gnais.search.grag import graph_rag_search
from gnais.search.rag import rag_search
from gnais.search.ragent import hybrid_search


def get_dataset(
    dataset_path: str,
    column_names: list[str] = ["query", "answer"],
) -> list[dspy.Example]:
    data = pd.read_csv(
        dataset_path,
        sep="\t",
        usecols=column_names,
    )
    data_dicts = data[column_names].to_dict(orient="records")
    evaluation_set = [
        dspy.Example({name: x[name] for name in column_names}).with_inputs(
            column_names[0]
        )
        for x in data_dicts
    ]
    return evaluation_set


def mark(
    query: str,
    generated_response: str,
    true_response: str,
) -> float:

    assess = dspy.ChainOfThought("question -> answer: int")
    context = f"""Your task is to compare informations (elements) in the answer generated by AI to the ones in the true answer.
    User query: {query}\nAI answer: {generated_response}\nTrue answer: {true_response}"""

    tp_question = f"{context}\nHow many elements in the generated answer are also highlighted in the true answer?"
    tp_score = assess(question=tp_question).get("answer")

    fp_question = f"{context}\nHow many elements are present in the generated answer and do not appear at all in the true answer?"
    fp_score = assess(question=fp_question).get("answer")

    fn_question = f"{context}\nHow many elements feature in the true answer but not in the generated answer?"
    fn_score = assess(question=fn_question).get("answer")

    f1 = (2 * tp_score) / ((2 * tp_score) + fp_score + fn_score)

    return f1


def evaluator(
    gold: dspy.Example,
    pred: str,
    trace=None,
    pred_name=None,
    pred_trace=None,
) -> int:
    query = gold["query"]
    true_response = gold["answer"]
    score = mark(query, pred, true_response)
    return 1 if score >= 0.6 else 0


def run_eval(
    runner: dspy.Evaluate,
    evaluation_set: list[dspy.Example],
    system: Any,
) -> dspy.evaluate.EvaluationResult:

    def search_func(query: str) -> str:
        """Wrap hybrid search in a sync version that consume streaming tokens and return the final answer"""

        async def _consume():
            results = []
            async for result in system(query):
                results.append(result)
            return "\n\n".join(str(r) for r in results)

        return asyncio.run(_consume())

    search = dspy.Tool(
        name="search",
        desc="Answer the question asked by the user.",
        args={
            "query": {
                "type": "string",
                "desc": "question asked by the user",
            },
        },
        func=search_func,
    )

    class Signature(dspy.Signature):
        query: str = dspy.InputField(desc="User question")
        answer: str = dspy.OutputField(
            desc="Answer to user's query with enough details and explanations to make sense of it"
        )

    # Wrap hybrid search into a DSPy module that is compatible with DSPy evaluation
    program = dspy.ReAct(
        signature=Signature, tools=[search], max_iters=2
    )  # limit iterations

    return runner(program)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--env-file", default=".env", help="Path to .env file")
    args = parser.parse_args()

    load_dotenv(dotenv_path=args.env_file)

    DB_PATH = os.getenv("DB_PATH")
    DATASET_PATH = os.getenv("DATASET_PATH")
    OUTPUT_PATH = os.getenv("OUTPUT_PATH")
    SEED = int(os.getenv("SEED"))
    MODEL_NAME = os.getenv("MODEL_NAME")
    MODEL_TYPE = int(os.getenv("MODEL_TYPE"))
    N_ITERATIONS = int(os.getenv("N_ITERATIONS"))

    torch.manual_seed(SEED)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(SEED)

    if MODEL_TYPE == 0:
        llm = dspy.LM(
            model=f"openai/{MODEL_NAME}",
            api_base="http://localhost:7501/v1",
            api_key="local",
            model_type="chat",
            max_tokens=10_000,
            n_ctx=10_000,
            seed=2_025,
            temperature=0,
            verbose=False,
        )
    elif MODEL_TYPE == 1:
        API_KEY = os.getenv("API_KEY")
        llm = dspy.LM(
            MODEL_NAME,
            api_key=API_KEY,
            max_tokens=10_000,
            temperature=0,
            verbose=False,
        )
    else:
        raise ValueError("MODEL_TYPE must be 0 or 1")

    dspy.configure(lm=llm)
    evaluation_set = get_dataset(DATASET_PATH)
    evaluate = dspy.Evaluate(
        devset=evaluation_set,
        metric=evaluator,
        num_threads=1,
        provide_traceback=True,
        display_table=False,
        display_progress=True,
        lm=llm,
    )
    collection = {}

    # Run evaluation set with LLM only
    base = dspy.ChainOfThought("query -> answer: str")
    base_output = [evaluate(base).get("score") for n in range(N_ITERATIONS)]
    collection["base"] = base_output

    # Run evaluation set with GN systems
    for system in [rag_search, graph_rag_search, agent_search, hybrid_search]:
        print(f"Running evaluation for {system}")
        temp = []
        for n in range(N_ITERATIONS):
            print(f"Iteration {n+1}")
            system_output = run_eval(evaluate, evaluation_set, system)
            temp.append(system_output.get("score"))
        collection[system.__name__] = temp
        print(f"Evaluation completed for {system}")
    final = pd.DataFrame(collection)
    final.to_csv(OUTPUT_PATH, index=False)
